name = "Nova ✰⋆⁺"
description = ""
keywords = ""
image = "pfp.webp"
theme = "dark"
primary_color = "#3de38b"
text_align = "center"
gtag_id = ""
base_url = "https://novaheic.github.io/"

[[sections]]
title = "Links"
description = ""
direction = "column"
item_style = "outline"
[[sections.items]]
title = "The Hitchhiker’s guide to the blockchain"
description = "A collection of videos and resources to help anyone understand the basics of blockchain technology and digital assets."
url = "https://medium.com/@cedricheidt/the-hitchhikers-guide-to-the-blockchain-a-collection-of-resources-e633a4e81a32"
[[sections.items]]
title = "Finzen"
description = "All-in-one personal finance dashboard I'm working on. Early access coming soon!"
url = "https://finzen.org/"
[[sections.items]]
title = "Reach out on Linkedin"
description = ""
url = "https://www.linkedin.com/in/nova-heidt/"

